#!/bin/sh -e

ORG_PATH="github.com/takahi-i"
REPO_PATH="${ORG_PATH}/walter-integration-test"

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export GOFMTPATH=" ./utils ./pipelines ./messengers"

rm -f ${GOPATH}/src/${REPO_PATH}
mkdir -p ${GOPATH}/src/${ORG_PATH}
ln -s ${PWD} ${GOPATH}/src/${REPO_PATH}

eval $(go env)

if ! [ -e $GOBIN/godep ]; then
    go get github.com/tools/godep
fi

if ! [ -e walter ]; then
    git clone git@github.com:walter-cd/walter.git
    cd walter; ./build; cp bin/walter $GOBIN
fi

$GOBIN/godep restore
