#!/bin/sh -e

ORG_PATH="github.com/walter-cd"
REPO_PATH="${ORG_PATH}/walter-integration-test"

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export GOFMTPATH=" ./utils ./pipelines ./messengers ./services"
export PATH=${GOBIN}:${PATH}

rm -f ${GOPATH}/src/${REPO_PATH}
mkdir -p ${GOPATH}/src/${ORG_PATH}
ln -s ${PWD} ${GOPATH}/src/${REPO_PATH}

eval $(go env)

if ! [ -e $GOBIN/godep ]; then
    go get github.com/tools/godep
fi

# download and compile the latest walter
if ! [ -e walter ]; then
    git clone git@github.com:walter-cd/walter.git
    cd walter; ./build; cp bin/walter $GOBIN
fi

# download sample repository hosted in github
if ! [ -e walter-github-sample-for-test ]; then
    git clone git@github.com:walter-cd/walter-github-sample-for-test.git
fi

$GOBIN/godep restore
